[2024-02-12 14:01:52,441] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: sales_mart.update_d_customer manual__2024-02-12T13:59:54.803582+00:00 [queued]>
[2024-02-12 14:01:52,447] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: sales_mart.update_d_customer manual__2024-02-12T13:59:54.803582+00:00 [queued]>
[2024-02-12 14:01:52,447] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-02-12 14:01:52,447] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-02-12 14:01:52,447] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-02-12 14:01:52,452] {taskinstance.py:1377} INFO - Executing <Task(PostgresOperator): update_d_customer> on 2024-02-12 13:59:54.803582+00:00
[2024-02-12 14:01:52,455] {standard_task_runner.py:52} INFO - Started process 27218 to run task
[2024-02-12 14:01:52,456] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'sales_mart', 'update_d_customer', 'manual__2024-02-12T13:59:54.803582+00:00', '--job-id', '519', '--raw', '--subdir', 'DAGS_FOLDER/sales_mart.py', '--cfg-path', '/tmp/tmp4ffwbtcz', '--error-file', '/tmp/tmpsa551wa1']
[2024-02-12 14:01:52,457] {standard_task_runner.py:80} INFO - Job 519: Subtask update_d_customer
[2024-02-12 14:01:52,499] {task_command.py:369} INFO - Running <TaskInstance: sales_mart.update_d_customer manual__2024-02-12T13:59:54.803582+00:00 [running]> on host 91766ce79ef0
[2024-02-12 14:01:52,536] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=student@example.com
AIRFLOW_CTX_DAG_OWNER=student
AIRFLOW_CTX_DAG_ID=sales_mart
AIRFLOW_CTX_TASK_ID=update_d_customer
AIRFLOW_CTX_EXECUTION_DATE=2024-02-12T13:59:54.803582+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-02-12T13:59:54.803582+00:00
[2024-02-12 14:01:52,542] {base.py:68} INFO - Using connection ID 'postgresql_de' for task execution.
[2024-02-12 14:01:52,546] {sql.py:315} INFO - Running statement: insert into mart.d_customer (customer_id, first_name, last_name, city_id)
select customer_id, first_name, last_name, max(city_id) from staging.user_order_log
where customer_id not in (select customer_id from mart.d_customer)
group by customer_id, first_name, last_name, parameters: None
[2024-02-12 14:01:52,553] {sql.py:324} INFO - Rows affected: 1822
[2024-02-12 14:01:52,563] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=sales_mart, task_id=update_d_customer, execution_date=20240212T135954, start_date=20240212T140152, end_date=20240212T140152
[2024-02-12 14:01:52,588] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-02-12 14:01:52,614] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
