[2024-02-12 10:12:22,548] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: sales_mart_inc.update_d_customer scheduled__2024-02-08T10:05:47.421232+00:00 [queued]>
[2024-02-12 10:12:22,553] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: sales_mart_inc.update_d_customer scheduled__2024-02-08T10:05:47.421232+00:00 [queued]>
[2024-02-12 10:12:22,554] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-02-12 10:12:22,554] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-02-12 10:12:22,554] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-02-12 10:12:22,559] {taskinstance.py:1377} INFO - Executing <Task(PostgresOperator): update_d_customer> on 2024-02-08 10:05:47.421232+00:00
[2024-02-12 10:12:22,562] {standard_task_runner.py:52} INFO - Started process 20916 to run task
[2024-02-12 10:12:22,563] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'sales_mart_inc', 'update_d_customer', 'scheduled__2024-02-08T10:05:47.421232+00:00', '--job-id', '459', '--raw', '--subdir', 'DAGS_FOLDER/sales_mart_inc.py', '--cfg-path', '/tmp/tmprt6wt0c_', '--error-file', '/tmp/tmput_binpq']
[2024-02-12 10:12:22,563] {standard_task_runner.py:80} INFO - Job 459: Subtask update_d_customer
[2024-02-12 10:12:22,594] {task_command.py:369} INFO - Running <TaskInstance: sales_mart_inc.update_d_customer scheduled__2024-02-08T10:05:47.421232+00:00 [running]> on host 91766ce79ef0
[2024-02-12 10:12:22,628] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=student@example.com
AIRFLOW_CTX_DAG_OWNER=student
AIRFLOW_CTX_DAG_ID=sales_mart_inc
AIRFLOW_CTX_TASK_ID=update_d_customer
AIRFLOW_CTX_EXECUTION_DATE=2024-02-08T10:05:47.421232+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-02-08T10:05:47.421232+00:00
[2024-02-12 10:12:22,634] {base.py:68} INFO - Using connection ID 'postgresql_de' for task execution.
[2024-02-12 10:12:22,638] {sql.py:315} INFO - Running statement: insert into mart.d_customer (customer_id, first_name, last_name, city_id)
select customer_id, first_name, last_name, max(city_id) from staging.user_order_log
where customer_id not in (select customer_id from mart.d_customer)
group by customer_id, first_name, last_name, parameters: None
[2024-02-12 10:12:22,639] {sql.py:324} INFO - Rows affected: 31
[2024-02-12 10:12:22,648] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=sales_mart_inc, task_id=update_d_customer, execution_date=20240208T100547, start_date=20240212T101222, end_date=20240212T101222
[2024-02-12 10:12:22,696] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-02-12 10:12:22,721] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
