[2024-02-11 22:39:07,847] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: sales_mart.update_d_customer scheduled__2024-02-06T22:34:02.383162+00:00 [queued]>
[2024-02-11 22:39:07,853] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: sales_mart.update_d_customer scheduled__2024-02-06T22:34:02.383162+00:00 [queued]>
[2024-02-11 22:39:07,853] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-02-11 22:39:07,853] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-02-11 22:39:07,853] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-02-11 22:39:07,860] {taskinstance.py:1377} INFO - Executing <Task(PostgresOperator): update_d_customer> on 2024-02-06 22:34:02.383162+00:00
[2024-02-11 22:39:07,863] {standard_task_runner.py:52} INFO - Started process 44624 to run task
[2024-02-11 22:39:07,864] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'sales_mart', 'update_d_customer', 'scheduled__2024-02-06T22:34:02.383162+00:00', '--job-id', '1084', '--raw', '--subdir', 'DAGS_FOLDER/sprint3 copy.py', '--cfg-path', '/tmp/tmpylvso_h0', '--error-file', '/tmp/tmpy_w2elf5']
[2024-02-11 22:39:07,865] {standard_task_runner.py:80} INFO - Job 1084: Subtask update_d_customer
[2024-02-11 22:39:07,898] {task_command.py:369} INFO - Running <TaskInstance: sales_mart.update_d_customer scheduled__2024-02-06T22:34:02.383162+00:00 [running]> on host 2a8d1eb5116f
[2024-02-11 22:39:07,935] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=student@example.com
AIRFLOW_CTX_DAG_OWNER=student
AIRFLOW_CTX_DAG_ID=sales_mart
AIRFLOW_CTX_TASK_ID=update_d_customer
AIRFLOW_CTX_EXECUTION_DATE=2024-02-06T22:34:02.383162+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-02-06T22:34:02.383162+00:00
[2024-02-11 22:39:07,941] {base.py:68} INFO - Using connection ID 'postgresql_de' for task execution.
[2024-02-11 22:39:07,945] {sql.py:315} INFO - Running statement: insert into mart.d_customer (customer_id, first_name, last_name, city_id)
select customer_id, first_name, last_name, max(city_id) from staging.user_order_log
where customer_id not in (select customer_id from mart.d_customer)
group by customer_id, first_name, last_name, parameters: None
[2024-02-11 22:39:07,946] {sql.py:324} INFO - Rows affected: 11
[2024-02-11 22:39:07,955] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=sales_mart, task_id=update_d_customer, execution_date=20240206T223402, start_date=20240211T223907, end_date=20240211T223907
[2024-02-11 22:39:07,997] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-02-11 22:39:08,015] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
