[2024-02-12 08:18:58,987] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: sales_mart_inc.update_f_sales scheduled__2024-02-10T08:09:37.968777+00:00 [queued]>
[2024-02-12 08:18:58,992] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: sales_mart_inc.update_f_sales scheduled__2024-02-10T08:09:37.968777+00:00 [queued]>
[2024-02-12 08:18:58,992] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-02-12 08:18:58,992] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-02-12 08:18:58,992] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-02-12 08:18:58,998] {taskinstance.py:1377} INFO - Executing <Task(PostgresOperator): update_f_sales> on 2024-02-10 08:09:37.968777+00:00
[2024-02-12 08:18:59,000] {standard_task_runner.py:52} INFO - Started process 14974 to run task
[2024-02-12 08:18:59,002] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'sales_mart_inc', 'update_f_sales', 'scheduled__2024-02-10T08:09:37.968777+00:00', '--job-id', '348', '--raw', '--subdir', 'DAGS_FOLDER/sales_mart_inc.py', '--cfg-path', '/tmp/tmpvdc_hipo', '--error-file', '/tmp/tmp0_ff3pnh']
[2024-02-12 08:18:59,002] {standard_task_runner.py:80} INFO - Job 348: Subtask update_f_sales
[2024-02-12 08:18:59,033] {task_command.py:369} INFO - Running <TaskInstance: sales_mart_inc.update_f_sales scheduled__2024-02-10T08:09:37.968777+00:00 [running]> on host 91766ce79ef0
[2024-02-12 08:18:59,068] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=student@example.com
AIRFLOW_CTX_DAG_OWNER=student
AIRFLOW_CTX_DAG_ID=sales_mart_inc
AIRFLOW_CTX_TASK_ID=update_f_sales
AIRFLOW_CTX_EXECUTION_DATE=2024-02-10T08:09:37.968777+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-02-10T08:09:37.968777+00:00
[2024-02-12 08:18:59,074] {base.py:68} INFO - Using connection ID 'postgresql_de' for task execution.
[2024-02-12 08:18:59,078] {sql.py:315} INFO - Running statement: insert into mart.f_sales (date_id, item_id, customer_id, city_id, quantity, payment_amount)
select 
    dc.date_id, 
    item_id, 
    customer_id, 
    city_id, 
    quantity, 
case when uol.status='refunded'  then payment_amount*-1 else payment_amount end as payment_amount
from staging.user_order_log uol
left join mart.d_calendar as dc on uol.date_time::Date = dc.date_actual
where uol.date_time::Date = '2024-02-10';, parameters: {'date': ('{{ ds }}',)}
[2024-02-12 08:18:59,085] {sql.py:324} INFO - Rows affected: 321
[2024-02-12 08:18:59,094] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=sales_mart_inc, task_id=update_f_sales, execution_date=20240210T080937, start_date=20240212T081858, end_date=20240212T081859
[2024-02-12 08:18:59,134] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-02-12 08:18:59,154] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
