[2024-02-12 10:01:19,210] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: sales_mart.update_d_customer manual__2024-02-12T09:59:49.063603+00:00 [queued]>
[2024-02-12 10:01:19,216] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: sales_mart.update_d_customer manual__2024-02-12T09:59:49.063603+00:00 [queued]>
[2024-02-12 10:01:19,216] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-02-12 10:01:19,216] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-02-12 10:01:19,216] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-02-12 10:01:19,221] {taskinstance.py:1377} INFO - Executing <Task(PostgresOperator): update_d_customer> on 2024-02-12 09:59:49.063603+00:00
[2024-02-12 10:01:19,224] {standard_task_runner.py:52} INFO - Started process 18389 to run task
[2024-02-12 10:01:19,225] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'sales_mart', 'update_d_customer', 'manual__2024-02-12T09:59:49.063603+00:00', '--job-id', '392', '--raw', '--subdir', 'DAGS_FOLDER/sales_mart.py', '--cfg-path', '/tmp/tmp3ayyibpy', '--error-file', '/tmp/tmpdb09ajlt']
[2024-02-12 10:01:19,226] {standard_task_runner.py:80} INFO - Job 392: Subtask update_d_customer
[2024-02-12 10:01:19,258] {task_command.py:369} INFO - Running <TaskInstance: sales_mart.update_d_customer manual__2024-02-12T09:59:49.063603+00:00 [running]> on host 91766ce79ef0
[2024-02-12 10:01:19,297] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=student@example.com
AIRFLOW_CTX_DAG_OWNER=student
AIRFLOW_CTX_DAG_ID=sales_mart
AIRFLOW_CTX_TASK_ID=update_d_customer
AIRFLOW_CTX_EXECUTION_DATE=2024-02-12T09:59:49.063603+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-02-12T09:59:49.063603+00:00
[2024-02-12 10:01:19,303] {base.py:68} INFO - Using connection ID 'postgresql_de' for task execution.
[2024-02-12 10:01:19,306] {sql.py:315} INFO - Running statement: insert into mart.d_customer (customer_id, first_name, last_name, city_id)
select customer_id, first_name, last_name, max(city_id) from staging.user_order_log
where customer_id not in (select customer_id from mart.d_customer)
group by customer_id, first_name, last_name, parameters: None
[2024-02-12 10:01:19,308] {sql.py:324} INFO - Rows affected: 0
[2024-02-12 10:01:19,317] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=sales_mart, task_id=update_d_customer, execution_date=20240212T095949, start_date=20240212T100119, end_date=20240212T100119
[2024-02-12 10:01:19,357] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-02-12 10:01:19,383] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
