[2024-02-12 07:34:13,194] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: sales_mart_inc.upload_user_order_inc scheduled__2024-02-07T07:30:05.907678+00:00 [queued]>
[2024-02-12 07:34:13,199] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: sales_mart_inc.upload_user_order_inc scheduled__2024-02-07T07:30:05.907678+00:00 [queued]>
[2024-02-12 07:34:13,199] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-02-12 07:34:13,199] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-02-12 07:34:13,199] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-02-12 07:34:13,204] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): upload_user_order_inc> on 2024-02-07 07:30:05.907678+00:00
[2024-02-12 07:34:13,207] {standard_task_runner.py:52} INFO - Started process 4609 to run task
[2024-02-12 07:34:13,209] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'sales_mart_inc', 'upload_user_order_inc', 'scheduled__2024-02-07T07:30:05.907678+00:00', '--job-id', '77', '--raw', '--subdir', 'DAGS_FOLDER/sprint3 copy 2.py', '--cfg-path', '/tmp/tmps4nfo10o', '--error-file', '/tmp/tmppruhbkip']
[2024-02-12 07:34:13,209] {standard_task_runner.py:80} INFO - Job 77: Subtask upload_user_order_inc
[2024-02-12 07:34:13,238] {task_command.py:369} INFO - Running <TaskInstance: sales_mart_inc.upload_user_order_inc scheduled__2024-02-07T07:30:05.907678+00:00 [running]> on host 91766ce79ef0
[2024-02-12 07:34:13,272] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=student@example.com
AIRFLOW_CTX_DAG_OWNER=student
AIRFLOW_CTX_DAG_ID=sales_mart_inc
AIRFLOW_CTX_TASK_ID=upload_user_order_inc
AIRFLOW_CTX_EXECUTION_DATE=2024-02-07T07:30:05.907678+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-02-07T07:30:05.907678+00:00
[2024-02-12 07:34:13,272] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/usr/local/lib/python3.8/dist-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: upload_data_to_staging() missing 1 required positional argument: 'b_inc'
[2024-02-12 07:34:13,278] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=sales_mart_inc, task_id=upload_user_order_inc, execution_date=20240207T073005, start_date=20240212T073413, end_date=20240212T073413
[2024-02-12 07:34:13,283] {standard_task_runner.py:92} ERROR - Failed to execute job 77 for task upload_user_order_inc (upload_data_to_staging() missing 1 required positional argument: 'b_inc'; 4609)
[2024-02-12 07:34:13,301] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-02-12 07:34:13,323] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
