[2024-02-12 14:06:51,169] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: sales_mart_inc.update_f_sales scheduled__2024-02-07T14:01:59.240675+00:00 [queued]>
[2024-02-12 14:06:51,174] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: sales_mart_inc.update_f_sales scheduled__2024-02-07T14:01:59.240675+00:00 [queued]>
[2024-02-12 14:06:51,174] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-02-12 14:06:51,174] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-02-12 14:06:51,174] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-02-12 14:06:51,179] {taskinstance.py:1377} INFO - Executing <Task(PostgresOperator): update_f_sales> on 2024-02-07 14:01:59.240675+00:00
[2024-02-12 14:06:51,182] {standard_task_runner.py:52} INFO - Started process 28971 to run task
[2024-02-12 14:06:51,183] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'sales_mart_inc', 'update_f_sales', 'scheduled__2024-02-07T14:01:59.240675+00:00', '--job-id', '567', '--raw', '--subdir', 'DAGS_FOLDER/sales_mart_inc.py', '--cfg-path', '/tmp/tmpna7v9vhk', '--error-file', '/tmp/tmpy8y1su1s']
[2024-02-12 14:06:51,183] {standard_task_runner.py:80} INFO - Job 567: Subtask update_f_sales
[2024-02-12 14:06:51,214] {task_command.py:369} INFO - Running <TaskInstance: sales_mart_inc.update_f_sales scheduled__2024-02-07T14:01:59.240675+00:00 [running]> on host 91766ce79ef0
[2024-02-12 14:06:51,253] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=student@example.com
AIRFLOW_CTX_DAG_OWNER=student
AIRFLOW_CTX_DAG_ID=sales_mart_inc
AIRFLOW_CTX_TASK_ID=update_f_sales
AIRFLOW_CTX_EXECUTION_DATE=2024-02-07T14:01:59.240675+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-02-07T14:01:59.240675+00:00
[2024-02-12 14:06:51,260] {base.py:68} INFO - Using connection ID 'postgresql_de' for task execution.
[2024-02-12 14:06:51,264] {sql.py:315} INFO - Running statement: insert into mart.f_sales (date_id, item_id, customer_id, city_id, quantity, payment_amount)
select 
    dc.date_id, 
    item_id, 
    customer_id, 
    city_id, 
    quantity, 
case when uol.status='refunded'  then payment_amount*-1 else payment_amount end as payment_amount
from staging.user_order_log uol
left join mart.d_calendar as dc on uol.date_time::Date = dc.date_actual
where uol.date_time::Date = '2024-02-07';, parameters: {'date': ('{{ ds }}',)}
[2024-02-12 14:06:51,270] {sql.py:324} INFO - Rows affected: 327
[2024-02-12 14:06:51,281] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=sales_mart_inc, task_id=update_f_sales, execution_date=20240207T140159, start_date=20240212T140651, end_date=20240212T140651
[2024-02-12 14:06:51,315] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-02-12 14:06:51,335] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
