[2024-02-12 08:14:22,998] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: sales_mart_inc.update_d_customer scheduled__2024-02-07T08:09:37.968777+00:00 [queued]>
[2024-02-12 08:14:23,007] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: sales_mart_inc.update_d_customer scheduled__2024-02-07T08:09:37.968777+00:00 [queued]>
[2024-02-12 08:14:23,008] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-02-12 08:14:23,008] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-02-12 08:14:23,008] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-02-12 08:14:23,020] {taskinstance.py:1377} INFO - Executing <Task(PostgresOperator): update_d_customer> on 2024-02-07 08:09:37.968777+00:00
[2024-02-12 08:14:23,023] {standard_task_runner.py:52} INFO - Started process 13281 to run task
[2024-02-12 08:14:23,025] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'sales_mart_inc', 'update_d_customer', 'scheduled__2024-02-07T08:09:37.968777+00:00', '--job-id', '302', '--raw', '--subdir', 'DAGS_FOLDER/sales_mart_inc.py', '--cfg-path', '/tmp/tmpxfvyguid', '--error-file', '/tmp/tmpv220tz6f']
[2024-02-12 08:14:23,025] {standard_task_runner.py:80} INFO - Job 302: Subtask update_d_customer
[2024-02-12 08:14:23,070] {task_command.py:369} INFO - Running <TaskInstance: sales_mart_inc.update_d_customer scheduled__2024-02-07T08:09:37.968777+00:00 [running]> on host 91766ce79ef0
[2024-02-12 08:14:23,109] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=student@example.com
AIRFLOW_CTX_DAG_OWNER=student
AIRFLOW_CTX_DAG_ID=sales_mart_inc
AIRFLOW_CTX_TASK_ID=update_d_customer
AIRFLOW_CTX_EXECUTION_DATE=2024-02-07T08:09:37.968777+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-02-07T08:09:37.968777+00:00
[2024-02-12 08:14:23,118] {base.py:68} INFO - Using connection ID 'postgresql_de' for task execution.
[2024-02-12 08:14:23,121] {sql.py:315} INFO - Running statement: insert into mart.d_customer (customer_id, first_name, last_name, city_id)
select customer_id, first_name, last_name, max(city_id) from staging.user_order_log
where customer_id not in (select customer_id from mart.d_customer)
group by customer_id, first_name, last_name, parameters: None
[2024-02-12 08:14:23,123] {sql.py:324} INFO - Rows affected: 0
[2024-02-12 08:14:23,132] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=sales_mart_inc, task_id=update_d_customer, execution_date=20240207T080937, start_date=20240212T081422, end_date=20240212T081423
[2024-02-12 08:14:23,157] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-02-12 08:14:23,181] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
